#!/bin/sh -e

GREEN='\033[1;32m'
NC='\033[0m'

SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1

gum spin --spinner dot --title "Starting build..." -- \
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM "$@"

gum spin --spinner dot --title "Switching to new generation..." -- \
./result/sw/bin/darwin-rebuild switch --flake .#${SYSTEM_TYPE} "$@"

gum spin --spinner dot --title "Cleaning up..." -- \
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
