#!/bin/sh -e

GREEN='\033[1;32m'
NC='\033[0m'

FLAKE="macos"

GEN_NUM=$(/run/current-system/sw/bin/darwin-rebuild --list-generations \
    | sort -r \
    | gum choose --header "Select a generation to rollback:" \
    | awk '{print $1}'
)

gum spin --spinner dot --title "Rolling back to generation $GEN_NUM..." -- \
/run/current-system/sw/bin/darwin-rebuild switch --flake .#$FLAKE --switch-generation $GEN_NUM

echo "${GREEN}Rollback to generation $GEN_NUM complete!${NC}"
