name: Setup Nix with Cachix
description: Setup Nix environment with Cachix configuration
inputs:
  signingKey:
    description: Cachix signing key
    required: false
  authToken:
    description: Cachix auth token
    required: true
runs:
  using: composite
  steps:
    - name: 🏗️ Install Nix
      uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
    - name: 🏗️ Setup cachix
      uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: tolkonepiu
        signingKey: ${{ inputs.signingKey }}
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
