name: Setup Nix with Cachix
description: Setup Nix environment with Cachix configuration
inputs:
  signingKey:
    description: Cachix signing key
    required: false
  authToken:
    description: Cachix auth token
    required: true
runs:
  using: composite
  steps:
    - name: 🏗️ Install Nix
      uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
    - name: 🏗️ Setup cachix
      uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: tolkonepiu
        signingKey: ${{ inputs.signingKey }}
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
