name: Setup Nix with Cachix
description: Setup Nix environment with Cachix configuration
inputs:
  signingKey:
    description: Cachix signing key
    required: false
  authToken:
    description: Cachix auth token
    required: true
runs:
  using: composite
  steps:
    - name: 🏗️ Install Nix
      uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
    - name: 🏗️ Setup cachix
      uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: tolkonepiu
        signingKey: ${{ inputs.signingKey }}
        authToken: ${{ inputs.authToken }}
        extraPullNames: nix-community
