# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Dix Diff

on:
  pull_request:
    paths:
      - modules/**
      - configurations/**
      - overlays/**
      - flake.lock
      - flake.nix
    branches:
      - main

jobs:
  discover-configs:
    runs-on: ubuntu-latest
    outputs:
      darwin-configs: ${{ steps.discover.outputs.darwin-configs }}

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🏗️ Install Nix
        uses: ./.github/actions/setup-nix
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: 🔍 Discover configurations
        id: discover
        run: |
          darwin_configs=$(nix eval .#darwinConfigurations --apply builtins.attrNames --json 2>/dev/null || echo '[]')
          echo "darwin-configs=$darwin_configs" >> $GITHUB_OUTPUT

  diff-macos:
    needs: discover-configs
    if: ${{ fromJSON(needs.discover-configs.outputs.darwin-configs)[0] != null }}
    permissions:
      contents: read
    strategy:
      matrix:
        darwin-config: ${{ fromJSON(needs.discover-configs.outputs.darwin-configs) }}
    runs-on: macos-26
    timeout-minutes: 20
    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🏗️ Install Nix
        uses: ./.github/actions/setup-nix
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: 🚀 Generate nix diff (${{ matrix.darwin-config }})
        uses: natsukium/nix-diff-action@b5c316c6cafc8470037d7f330b178aaeeba96ba4 # v1.1.0
        with:
          mode: diff-only
          attributes: |
            - displayName: ${{ matrix.darwin-config }}
              attribute: darwinConfigurations.${{ matrix.darwin-config }}.config.system.build.toplevel

  comment:
    needs: diff-macos
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    steps:
      - name: 💬 Comment nix diff results
        uses: natsukium/nix-diff-action@b5c316c6cafc8470037d7f330b178aaeeba96ba4 # v1.1.0
        with:
          mode: comment-only
