# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-26
    runs-on: ${{ matrix.os }}

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🏗️ Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: 🚀 Check flake.lock
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12

      - name: 🚀 Run checks
        run: nix develop -c pre-commit run --all-files
