# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-26
    runs-on: ${{ matrix.os }}

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🏗️ Install Nix
        uses: ./.github/actions/setup-nix
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: 🚀 Check flake.lock
        uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # v13

      - name: 🚀 Run checks
        run: nix develop -c pre-commit run --all-files
